### ISSUE TITLE
problème affichage bloc titre data

### ISSUE THREAD

**Issue by HWFord** [geobretagne/mreport#112]
![image](https://user-images.githubusercontent.com/54360213/108068520-79f2e700-7062-11eb-8a46-5d66a7105bc5.png)

**Comment by HWFord** [comment]
Lié au données non configuré ?
![image](https://user-images.githubusercontent.com/54360213/108069859-2386a800-7064-11eb-9a5a-389051efa7df.png)

**Comment by spelhate** [comment]
Fixed with 57697ec
