### ISSUE TITLE
Pas de possibilité de re-fusion des cellules divisées dans un bloc

### ISSUE THREAD

**Issue by Clement-Bader-bzh** [geobretagne/mreport#164]
Lors de la mise en forme dans le composeur, il n'est pas possible de re-fusionner deux cellules après division horizontale ou verticale au sein d'un bloc.

![fusion_cellules](https://user-images.githubusercontent.com/77267495/158423617-d7034c61-4dcb-4762-8ee4-3e1a482dfb19.PNG)

**Comment by lecault** [comment]
Le soucis est qu'on est obligé de recommencer le bloc. Je partirai sur un bouton Annuler qui annule la division.
