### ISSUE TITLE
Infobulles graphe camembert

### ISSUE THREAD

**Issue by lecault** [geobretagne/mreport#49]
Lorsqu'on insère une dataviz de camembert, l'infobulle ne s'affiche pas correctement : 

![image](https://user-images.githubusercontent.com/5269430/86591637-3a273580-bf92-11ea-9d1c-166eb2101480.png)

Proposition simple : **Appartement: 44444**
Proposition plus complexe : mixer valeur absolue dans la taille et le pourcentage (il me semble demande SH) **Appartement : 62 %**

**Comment by Sfoucheur** [comment]
Salut, tu voudrais pouvoir configurer l'affichage du coup ?

**Comment by lecault** [comment]
Salut. 
Si déjà on peut avoir un affichage automatique dataset:data ça sera bien. 
Mais oui dans l'idéal qu'on puisse afficher un pourcentage calculer par la machine

**Comment by Sfoucheur** [comment]
Je viens de modifier les tooltips, il y a encore des problèmes mais dit moi déjà si ça correspond à ce que tu voulais

**Comment by lecault** [comment]
Je viens de voir, merci c'est top. 
Tu peux arrondir à une décimale ça sera suffisant. Et encore mieux, quand la valeur est entière (https://kartenn.region-bretagne.fr/mreport/epci_chiffres_cles/243500741) ne pas mettre de décimale du tout.

**Comment by Sfoucheur** [comment]
Je viens de modifier les tooltips pour qu'il n'y ai plus qu'une décimale et pas de zéros inutiles, dis moi si c'est bon pour toi

**Comment by lecault** [comment]
C'est bon tu peux fermer
