### ISSUE TITLE
Intégration iframe

### ISSUE THREAD

**Issue by lecault** [geobretagne/mreport#50]
Je vais avoir besoin d'intégrer une carte dynamique dans un rapport au travers d'une iframe via mreport.

Voici un exemple de code d'iframe : 

<div class="iframeconteneur">
  <iframe id="cooperation" width="100%" height="500" title="Coopération internationale" src="http://kartenn.region-bretagne.fr/kartoviz/?x=3362716&y=1350307&z=3&l=region_cooperation_internationale*&lb=positron&config=apps%2Fregion%2Fbretagne_bzh%2Fcooperation_internationale.xml&mode=u"></iframe>
</div>

Ce que je propose :
id : dataviz
title : label
src : data

**Comment by Sfoucheur** [comment]
Tu veux pouvoir créer un iframe sans avoir de dataviz associée ou alors utiliser les datavizs qui peuvent être sous forme d'iframe?

**Comment by lecault** [comment]
Il s'agit d'une dataviz (table rawdata) sous forme d'iframe.

**Comment by Sfoucheur** [comment]
Dans ce cas je pense que le problème est réglé, dis-moi quand tu auras testé pour que je close l'issue

**Comment by lecault** [comment]
Oui c'est bon : https://kartenn.region-bretagne.fr/mreport/epci_centralite/200069409
