### ISSUE TITLE
Composer et type image : ascenseurs

### ISSUE THREAD

**Issue by lecault** [geobretagne/mreport#62]
Depuis le composeur, si on ajoute une donnée de type image, il y a des ascenseurs qui apparaissent : elle n'est pas mise à l'échelle.

Avant : https://kartenn.region-bretagne.fr/mreport/qpv/QP029008
Maintenant : https://kartenn.region-bretagne.fr/mreport/qpv14/QP029008

**Comment by Sfoucheur** [comment]
Le problème viens du type iframe qui ne fonctionne pas avec les images il faut donc choisir le type image
