### ISSUE TITLE
Enregistrement impossible dataviz type image

### ISSUE THREAD

**Issue by lecault** [geobretagne/mreport#65]
Dans le composeur, je n'arrive pas à enregistrer un rapport avec une dataviz de type image.

Lorsque je clique sur enregistrer j'ai cette erreur : enregistrement échec :undefined

**Comment by spelhate** [comment]
C'est à cause du WAF. La requête POST est bloquée par le système de sécurité.

**Comment by lecault** [comment]
Problème région Résolu
