### ISSUE TITLE
Division d'un bloc structurant horizontalement, problème affichage

### ISSUE THREAD

**Issue by HWFord** [geobretagne/mreport#97]
lorsqu'on fait une division horizontale d'un bloc l'affichage sort de son cadre notamment avec la division en 3 partie

![image](https://user-images.githubusercontent.com/54360213/107530257-fba6c880-6bbb-11eb-9048-62e44ab197c3.png)

**Comment by spelhate** [comment]
Le bug intervient uniquement lors d'une division par 3
